### ISSUE TITLE
FOWARD Pig Fight

### ISSUE THREAD

**Issue by trevorkosht** [Collaborative-Software-Development-Club/Fall-2024-Unity-Game#43]
Implementation of features for the puzzle

create items to hide behind from pigs tongue
create a "laser beam" (the tongue) that will shoot at player after a dialogue message)

Once the pig eats the items that the player has been hiding behind in the order of the combination, create a win message.

if the player gets hit by the tongue then the player will get eaten and die.

after 4 items are eaten have the player get eaten and dies.  (implement your own way to to get the player to die)

Have the friendly hamster NPC appear

**Comment by calebcope** [comment]
Planning to create tongue projectile thing.
