### ISSUE TITLE
MAZE Functionality

### ISSUE THREAD

**Issue by trevorkosht** [Collaborative-Software-Development-Club/Fall-2024-Unity-Game#76]
Add Mini mushrooms

Change scale of maze

Add more interesting and dynamic paths
- Create areas that are clearly the correct way
- Create more traps that will kill

**Comment by csandcastle** [comment]
Probably mostly done, changing scale of maze fixed many play issues along with adding the mushrooms, didn't add kill traps since they likely aren't necessary, if play testing reveals that current maze isn't enough then it can be corrected. Not opening pull request until cutscene bug is fixed
